//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recommender.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        public Author()
        {
            this.Songs = new HashSet<Song>();
        }
    
        public int AuthorId { get; set; }
        public string AuthorName { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    
        public virtual ICollection<Song> Songs { get; set; }
    }
}
