//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recommender.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collection
    {
        public Collection()
        {
            this.Songs = new HashSet<Song>();
        }
    
        public int CollectionId { get; set; }
        public string CollectionName { get; set; }
        public Nullable<int> NumberSongs { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    
        public virtual ICollection<Song> Songs { get; set; }
    }
}
