//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recommender.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        public Song()
        {
            this.UserCollections = new HashSet<UserCollection>();
            this.AspNetUsers = new HashSet<AspNetUser>();
        }
    
        public int SongId { get; set; }
        public string SongTitle { get; set; }
        public int ArtistId { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public int GenreId { get; set; }
        public System.DateTime Timestamp { get; set; }
        public Nullable<double> Duration { get; set; }
        public int CollectionId { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Author Author { get; set; }
        public virtual Collection Collection { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual ICollection<UserCollection> UserCollections { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
    }
}
