//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recommender.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCollection
    {
        public UserCollection()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.Songs = new HashSet<Song>();
        }
    
        public int UserCollectionId { get; set; }
        public string UserCollectionName { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string UserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        public virtual ICollection<Song> Songs { get; set; }
    }
}
